version: "3.8"
services:
  api:
    build: .
    container_name: yellot_api
    network_mode: bridge
    ports:
      - "0.0.0.0:8001:8001"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
